---
title: "BAGIDIS_Testing"
author: "Tayeb Zaidi"
date: "October 27, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(Bagidis)
```

##  Download Image

```{r,message=FALSE,results='hide'}
# load image
myurl <- "http://www.macalester.edu/~dshuman1/data/cameraman.jpg"
z <- tempfile()
download.file(myurl,z,mode="wb")
im <- readJPEG(z)
file.remove(z) # cleanup
im=t(im)
d=dim(im)
M=d[1];
N=d[2];
if (M != N){warning('Image not square. This code assumes the image is square.')}
im=im[,c(N:1)]
```

```{r}
pImage <- function(im, ...) {
  image(im, col=gray((0:32)/32),...)
}
```

### BAGIDIS representation

```{r}
### Disabled because the runtime is too slow
#Bagidis.out.2D <- Bagidis::BUUHWE_2D(im)
#Bagidis::BUUHWE_2D.plot(Bagidis.out.2D)
```

## BAGIDIS representation of a lightcurve

#Generate lightcurves
```{r}
f1 <- function(t){20*sin(t)+exp(-t)}
f2 <- function(t){10*sin(t)+exp(-t)}
f3 <- function(t){10*sin(t)+exp(-t)+20}
tt = (0:200)/200
#Lightcurve 1
xx1 = f1(tt)
#Lightcurve 2
xx2 = f2(tt)
#Lightcurve 3
xx3 = f3(tt)
```

#View and get distances
```{r}
Bagidis.out.1 <- Bagidis::BUUHWE(xx1)
Bagidis::BUUHWE.plot(Bagidis.out.1)

Bagidis.out.2 <- Bagidis::BUUHWE(xx2)
Bagidis::BUUHWE.plot(Bagidis.out.2)

Bagidis.out.3 <- Bagidis::BUUHWE(xx3)
Bagidis::BUUHWE.plot(Bagidis.out.3)

Bagidis.out.3$detail
```

```{r}
Bagidis::BAGIDIS.dist(Bagidis.out.1,Bagidis.out.3)
```
